<a href="https://colab.research.google.com/github/Swapn2/Data-Science-Learnings/blob/main/advance_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array vs Python List

In [3]:
# python list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
import time
c = []
start = time.time()
for i in range(len(a)):
  c.append(a[i] +b[i])
print(time.time()-start)

3.3178083896636963


In [6]:
# Numpy array
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print(time.time()-start)

0.03305697441101074


In [7]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [10]:
a = np.arange(10000000,dtype = np.int16)
sys.getsizeof(a)

20000112

# Advance Indexing

In [17]:
# normal indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
a[1,2]

np.int64(6)

In [19]:
# fancy indexing
import numpy as np

# let say you need 1st , 3rd and 4th row

a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [21]:
a[:,[0,2,3]]  # extracting column

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [23]:
# Boolean indexing
import numpy as np

a = np.random.randint(1,100,24).reshape(6,4)
a

array([[37, 58, 83, 43],
       [14, 75, 86, 95],
       [56, 48, 88, 12],
       [71, 70, 83,  9],
       [13, 67, 34,  1],
       [99, 96, 57, 84]])

In [26]:
# find all the number greater than 50
# a > 50
a[a>50]   # boolean mask

array([58, 83, 75, 86, 95, 56, 88, 71, 70, 83, 67, 99, 96, 57, 84])

In [27]:
# find out even number
a[a%2 ==0 ]

array([58, 14, 86, 56, 48, 88, 12, 70, 34, 96, 84])

In [31]:
# find all the numbers greater than 50 and even
a[(a%2 == 0)&(a>50)]

array([58, 86, 56, 88, 70, 96, 84])