<a href="https://colab.research.google.com/github/Swapn2/Data-Science-Learnings/blob/main/Multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [59]:
data = load_diabetes()
x =data.data

In [60]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [61]:
x.shape

(442, 10)

In [62]:
y = data.target

In [63]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [64]:
y.shape

(442,)

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .2 , random_state = 32)

In [67]:
x_train

array([[ 0.06350368,  0.05068012,  0.08864151, ...,  0.07120998,
         0.02929656,  0.07348023],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       [ 0.03444337,  0.05068012, -0.02991782, ..., -0.00259226,
         0.02405509, -0.03835666],
       ...,
       [-0.00551455,  0.05068012,  0.00133873, ..., -0.03949338,
        -0.04117617, -0.08806194],
       [ 0.01991321, -0.04464164, -0.02345095, ..., -0.0763945 ,
        -0.04257085,  0.07348023],
       [ 0.02717829,  0.05068012,  0.09403057, ..., -0.00259226,
         0.03664373,  0.10661708]])

In [68]:
y_test.shape

(89,)

In [69]:
from sklearn.linear_model import LinearRegression

In [70]:
lr = LinearRegression()

In [71]:
lr.fit(x_train,y_train)

LinearRegression()

In [72]:
y_pred = lr.predict(x_test)

In [73]:
y_pred

array([172.60221563, 176.28452979, 104.69642913, 123.73172065,
       125.12918841, 175.52860928, 221.40057635, 160.84007097,
       216.01436124, 188.23526082,  95.28269009, 238.57773462,
       223.41312722,  69.82251258, 105.75775874,  55.78523953,
       116.04227362, 146.99512516, 178.52120042, 147.16269541,
       110.60045446, 156.88298979,  82.30039499, 185.56700021,
       145.63102069, 165.09136947, 291.18274014, 242.86916518,
       211.93210439, 287.45873377, 196.59135902, 127.43771823,
       209.84018734, 183.1606271 , 150.20425299, 114.49182187,
       195.96246781, 213.03006633,  99.00218774,  91.55574708,
       225.40664872, 103.49093388, 133.76320566, 160.23604055,
       137.48284804, 141.62538982, 157.64325814,  90.51604444,
       173.31917991, 232.56143464, 165.0880776 , 147.67363064,
       169.44439603, 211.64268676, 152.86666838, 108.86805754,
       122.6790726 , 171.54184272, 170.17264755, 207.48159075,
       219.34541916, 164.91624615, 179.59840729, 109.11

In [74]:
y_pred.shape

(89,)

In [75]:
from sklearn.metrics import r2_score

In [76]:
r2_score(y_test,y_pred)

0.4522338796354569

In [77]:
r2_score(y_pred,y_test)

-0.04323272518850163

In [78]:
lr.coef_

array([  32.50000078, -274.2083569 ,  501.52744069,  368.7931961 ,
       -822.31120988,  504.23867319,  101.57697155,  158.16545687,
        744.91541712,   78.40553632])

In [79]:
lr.intercept_

np.float64(154.31230345901605)

In [84]:
class MyLr:
  def __init__(self):
    self.coef = None
    self.intercept = None

  def fit(self,x_train,y_train):
    x_train = np.insert(x_train,0,1,axis = 1)

    betas = np.linalg.inv(x_train.T.dot(x_train)).dot(x_train.T).dot(y_train)
    self.intercept = betas[0]
    self.coef = betas[1:]

  def predict(self,x_test):
    y_pred = np.dot(x_test,self.coef) + self.intercept
    return y_pred

In [85]:
lr = MyLr()

In [86]:
print(x_train.shape)
print(y_train.shape)
print(x_train.T.shape)

(353, 10)
(353,)
(10, 353)


In [87]:
lr.fit(x_train,y_train)

In [89]:
y_pred = lr.predict(x_test)

In [90]:
y_pred

array([172.60221563, 176.28452979, 104.69642913, 123.73172065,
       125.12918841, 175.52860928, 221.40057635, 160.84007097,
       216.01436124, 188.23526082,  95.28269009, 238.57773462,
       223.41312722,  69.82251258, 105.75775874,  55.78523953,
       116.04227362, 146.99512516, 178.52120042, 147.16269541,
       110.60045446, 156.88298979,  82.30039499, 185.56700021,
       145.63102069, 165.09136947, 291.18274014, 242.86916518,
       211.93210439, 287.45873377, 196.59135902, 127.43771823,
       209.84018734, 183.1606271 , 150.20425299, 114.49182187,
       195.96246781, 213.03006633,  99.00218774,  91.55574708,
       225.40664872, 103.49093388, 133.76320566, 160.23604055,
       137.48284804, 141.62538982, 157.64325814,  90.51604444,
       173.31917991, 232.56143464, 165.0880776 , 147.67363064,
       169.44439603, 211.64268676, 152.86666838, 108.86805754,
       122.6790726 , 171.54184272, 170.17264755, 207.48159075,
       219.34541916, 164.91624615, 179.59840729, 109.11

In [91]:
r2_score(y_test,y_pred)

0.4522338796354567