<a href="https://colab.research.google.com/github/Swapn2/Data-Science-Learnings/blob/main/NumPy_trick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np

a = np.random.randint(1,100,15)
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 71, 99, 54],
       [69,  1, 59, 48],
       [19, 34, 22, 23],
       [13, 17, 20, 89],
       [64, 81, 17, 29],
       [35, 85, 88, 75]])

In [3]:
np.sort(a)

array([ 6, 23, 26, 34, 36, 40, 48, 57, 59, 61, 77, 78, 80, 80, 91])

In [6]:
np.sort(a)[::-1] # decending preder

array([91, 80, 80, 78, 77, 61, 59, 57, 48, 40, 36, 34, 26, 23,  6])

In [5]:
np.sort(b,axis=0)

array([[10,  1, 17, 23],
       [13, 17, 20, 29],
       [19, 34, 22, 48],
       [35, 71, 59, 54],
       [64, 81, 88, 75],
       [69, 85, 99, 89]])