<a href="https://colab.research.google.com/github/Swapn2/Data-Science-Learnings/blob/main/NumPy_trick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np

a = np.random.randint(1,100,15)
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 71, 99, 54],
       [69,  1, 59, 48],
       [19, 34, 22, 23],
       [13, 17, 20, 89],
       [64, 81, 17, 29],
       [35, 85, 88, 75]])

In [3]:
np.sort(a)

array([ 6, 23, 26, 34, 36, 40, 48, 57, 59, 61, 77, 78, 80, 80, 91])

In [6]:
np.sort(a)[::-1] # decending preder

array([91, 80, 80, 78, 77, 61, 59, 57, 48, 40, 36, 34, 26, 23,  6])

In [5]:
np.sort(b,axis=0)

array([[10,  1, 17, 23],
       [13, 17, 20, 29],
       [19, 34, 22, 48],
       [35, 71, 59, 54],
       [64, 81, 88, 75],
       [69, 85, 99, 89]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
np.append(a,200)

array([ 36,  80,  61,  80,  26,  48,  40,  77,  91,  23,  34,  57,  78,
         6,  59, 200])

In [8]:
b

array([[10, 71, 99, 54],
       [69,  1, 59, 48],
       [19, 34, 22, 23],
       [13, 17, 20, 89],
       [64, 81, 17, 29],
       [35, 85, 88, 75]])

In [9]:
np.append(b,np.ones((b.shape[0],1)))

array([10., 71., 99., 54., 69.,  1., 59., 48., 19., 34., 22., 23., 13.,
       17., 20., 89., 64., 81., 17., 29., 35., 85., 88., 75.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [10]:
np.append(b,np.ones((b.shape[0],1)),axis = 1 )

array([[10., 71., 99., 54.,  1.],
       [69.,  1., 59., 48.,  1.],
       [19., 34., 22., 23.,  1.],
       [13., 17., 20., 89.,  1.],
       [64., 81., 17., 29.,  1.],
       [35., 85., 88., 75.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [11]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis = 1 )

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [16]:
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

In [17]:
np.expand_dims(a,axis=0)

array([[36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59]])

In [19]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1)

array([[36],
       [80],
       [61],
       [80],
       [26],
       [48],
       [40],
       [77],
       [91],
       [23],
       [34],
       [57],
       [78],
       [ 6],
       [59]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [21]:
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

In [22]:
np.where(a>50)

(array([ 1,  2,  3,  7,  8, 11, 12, 14]),)

In [23]:
np.where(a>50,0,a)

array([36,  0,  0,  0, 26, 48, 40,  0,  0, 23, 34,  0,  0,  6,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [24]:
np.argmax(a)

np.int64(8)

In [25]:
b

array([[10, 71, 99, 54],
       [69,  1, 59, 48],
       [19, 34, 22, 23],
       [13, 17, 20, 89],
       [64, 81, 17, 29],
       [35, 85, 88, 75]])

In [26]:
np.argmax(b,axis = 0)  # columwise max

array([1, 5, 0, 3])

In [28]:
np.argmax(b,axis = 1)  # row max

array([2, 0, 1, 3, 1, 2])

In [29]:
np.cumsum(b)

array([  10,   81,  180,  234,  303,  304,  363,  411,  430,  464,  486,
        509,  522,  539,  559,  648,  712,  793,  810,  839,  874,  959,
       1047, 1122])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [30]:
np.percentile(a,0)

np.float64(6.0)

In [31]:
np.percentile(a,100)

np.float64(91.0)

In [32]:
np.percentile(a,50)

np.float64(57.0)

In [33]:
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [34]:
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

In [35]:
np.histogram(a,bins=[10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 2, 2, 2, 1, 2, 2, 1]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [36]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [37]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([80, 80, 40])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [38]:
np.flip(a)

array([59,  6, 78, 57, 34, 23, 91, 77, 40, 48, 26, 80, 61, 80, 36])

In [39]:
np.flip(b,axis=1)

array([[54, 99, 71, 10],
       [48, 59,  1, 69],
       [23, 22, 34, 19],
       [89, 20, 17, 13],
       [29, 17, 81, 64],
       [75, 88, 85, 35]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [40]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [41]:
np.delete(a,[0,2,4])

array([530,  80,  48,  40,  77,  91,  23,  34,  57,  78,   6,  59])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [42]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
np.intersect1d(m,n)

array([3, 4, 5])

In [44]:
np.setdiff1d(n,m)

array([6, 7])

In [45]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [46]:
m[np.in1d(m,1)]

<ipython-input-46-3d5a78555eb5>:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [47]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 61, 75, 26, 48, 40, 75, 75, 25, 34, 57, 75, 25, 59])