<a href="https://colab.research.google.com/github/Swapn2/Data-Science-Learnings/blob/main/Numpy_fundmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## creating numpy array


In [4]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [7]:
# dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [8]:
# dtype
np.array([1,2,3],dtype = bool)


array([ True,  True,  True])

In [9]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
# with reshape
np.arange(1,17).reshape(2,2,2,2)  # 4D array

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [13]:
# np.ones and np.zeros
np.ones((3,4))

# this useful fir itnialzing the weights of neural network

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# np.random
np.random.random((3,4))

array([[0.79957379, 0.11155262, 0.4533272 , 0.97605653],
       [0.21704022, 0.51867861, 0.80541752, 0.58036548],
       [0.64423939, 0.46267876, 0.56306147, 0.92867043]])

In [15]:
# np.linspace
np.linspace(-10,10,10)

# (star , end , no of item you want )


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [16]:
# np.linspace
np.linspace(-10,10,10, dtype=int)

# (star , end , no of item you want )


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [17]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [18]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [19]:
a3.ndim

3

In [20]:
# shape
a2.shape

(3, 4)

In [21]:
a3.shape

(2, 2, 2)

In [22]:
# size
a3.size

8

In [23]:
a2.size

12

In [24]:
# itemsize
a.itemsize

8

In [25]:
a4 = np.arange(10,dtype = np.int32)

In [26]:
a4.itemsize

4

### Changing Datatype

In [27]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [28]:
# arithmetic operation

a2 *2

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [29]:
# relational

a2 >2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Array Functions

In [30]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[21., 16., 36.],
       [93., 57., 65.],
       [98., 12., 16.]])

In [31]:
np.max(a1,axis = 1 )
# 0 -> column
# 1 - > row

array([36., 93., 98.])

In [32]:
np.min(a1)

np.float64(12.0)

In [33]:
np.sum(a1 , axis = 1)

array([ 73., 215., 126.])

In [34]:
np.prod(a1)

np.float64(78422420643840.0)

In [35]:
# mean / median / mode
np.mean(a1)

np.float64(46.0)

In [36]:
np.mean(a1 , axis = 1)

array([24.33333333, 71.66666667, 42.        ])

In [37]:
np.median(a1 , axis = 1)

array([21., 65., 16.])

In [53]:
np.mode(a1 , axis = 1)

AttributeError: module 'numpy' has no attribute 'mode'

In [54]:
np.var(a1 , axis = 1)

array([  72.22222222,  238.22222222, 1570.66666667])

In [55]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

In [56]:
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [57]:
# round/ floor / ceil
np.round(np.random.random((3,4))*100)

array([[24., 65., 53., 27.],
       [77., 98., 74.,  9.],
       [98., 68., 76., 89.]])

In [58]:
# round/ floor / ceil
np.floor(np.random.random((3,4))*100)

array([[66., 40., 45.,  2.],
       [57., 41., 65., 72.],
       [31.,  9., 23.,  5.]])

### Indexing and Slicing

In [59]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a1[-1]

np.int64(9)

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
# lets extract 6
a2[1,2]
# lets exract 10
a2[2,2]

np.int64(10)

In [64]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [65]:
# lets extract 5
a3[1,0,1]

np.int64(5)

In [66]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a1[2:5:2]

array([2, 4])

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a2[0,:] # extract row 1

array([0, 1, 2, 3])

In [70]:
a2[:,2]  # extract colum 2

array([ 2,  6, 10])

In [71]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [72]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [73]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [75]:
a2[1,::3]

array([4, 7])

In [78]:
a3= np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [81]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
a3[0][1]

array([3, 4, 5])

In [85]:
a3[1][:,1]

array([10, 13, 16])

In [86]:
a3[2][1:3,1:]

array([[22, 23],
       [25, 26]])

In [93]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# iterating


In [100]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [101]:
a2

for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [102]:
a3

for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [103]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## reshaping

In [104]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [106]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [107]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [108]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# stacking

In [109]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


In [111]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [112]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting

In [113]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [116]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]