<a href="https://colab.research.google.com/github/Swapn2/Data-Science-Learnings/blob/main/NumPy_trick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np

a = np.random.randint(1,100,15)
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 71, 99, 54],
       [69,  1, 59, 48],
       [19, 34, 22, 23],
       [13, 17, 20, 89],
       [64, 81, 17, 29],
       [35, 85, 88, 75]])

In [3]:
np.sort(a)

array([ 6, 23, 26, 34, 36, 40, 48, 57, 59, 61, 77, 78, 80, 80, 91])

In [6]:
np.sort(a)[::-1] # decending preder

array([91, 80, 80, 78, 77, 61, 59, 57, 48, 40, 36, 34, 26, 23,  6])

In [5]:
np.sort(b,axis=0)

array([[10,  1, 17, 23],
       [13, 17, 20, 29],
       [19, 34, 22, 48],
       [35, 71, 59, 54],
       [64, 81, 88, 75],
       [69, 85, 99, 89]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
np.append(a,200)

array([ 36,  80,  61,  80,  26,  48,  40,  77,  91,  23,  34,  57,  78,
         6,  59, 200])

In [8]:
b

array([[10, 71, 99, 54],
       [69,  1, 59, 48],
       [19, 34, 22, 23],
       [13, 17, 20, 89],
       [64, 81, 17, 29],
       [35, 85, 88, 75]])

In [9]:
np.append(b,np.ones((b.shape[0],1)))

array([10., 71., 99., 54., 69.,  1., 59., 48., 19., 34., 22., 23., 13.,
       17., 20., 89., 64., 81., 17., 29., 35., 85., 88., 75.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [10]:
np.append(b,np.ones((b.shape[0],1)),axis = 1 )

array([[10., 71., 99., 54.,  1.],
       [69.,  1., 59., 48.,  1.],
       [19., 34., 22., 23.,  1.],
       [13., 17., 20., 89.,  1.],
       [64., 81., 17., 29.,  1.],
       [35., 85., 88., 75.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [11]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis = 1 )

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [16]:
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

In [17]:
np.expand_dims(a,axis=0)

array([[36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59]])

In [19]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1)

array([[36],
       [80],
       [61],
       [80],
       [26],
       [48],
       [40],
       [77],
       [91],
       [23],
       [34],
       [57],
       [78],
       [ 6],
       [59]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [21]:
a

array([36, 80, 61, 80, 26, 48, 40, 77, 91, 23, 34, 57, 78,  6, 59])

In [22]:
np.where(a>50)

(array([ 1,  2,  3,  7,  8, 11, 12, 14]),)

In [23]:
np.where(a>50,0,a)

array([36,  0,  0,  0, 26, 48, 40,  0,  0, 23, 34,  0,  0,  6,  0])